### ISSUE TITLE
The following packages have unmet dependencies:  tensorflow-1.12-cuda-10.0

### ISSUE THREAD

**Issue by emmanuelroque** [system76/cuda#10]
I'm using Pop OS 18.10, I tried to install tensorflow but the following errors were found:

sudo apt install tensorflow-1.12-cuda-10.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tensorflow-1.12-cuda-10.0 : Depends: python3-keras (>= 2.2.2) but it is not going to be installed
                             Depends: python3-keras-applications (>= 1.0.5) but it is not installable
                             Depends: python3-keras-preprocessing (>= 1.0.3) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by mmstick** [comment]
You must not have Pop's PPA enabled:

```
# apt-cache policy python3-keras python3-keras-applications python3-keras-preprocessing
python3-keras:
  Installed: 2.2.2-1pop1
  Candidate: 2.2.2-1pop1
  Version table:
 *** 2.2.2-1pop1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
     2.1.5-2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu cosmic/universe i386 Packages
python3-keras-applications:
  Installed: 1.0.6-1pop1
  Candidate: 1.0.6-1pop1
  Version table:
 *** 1.0.6-1pop1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
python3-keras-preprocessing:
  Installed: 1.0.3-1pop1
  Candidate: 1.0.3-1pop1
  Version table:
 *** 1.0.3-1pop1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by emmanuelroque** [comment]
Oh you're right, that was my mistake, I'm sorry, thank you very much for your response. Now it works :)
