### ISSUE TITLE
Why /usr/lib instead of /usr/local ?

### ISSUE THREAD

**Issue by lhk** [system76/cuda#13]
This package installs cuda to` /usr/lib`. However, the default seems to be` /usr/local`. For example, the mnistCUDNN sample code from the [code samples available here](https://developer.nvidia.com/rdp/cudnn-download) only compiles after editing the Makefile to your path.

I've tried torch and it works fine. But there are packages that rely on the /usr/local as the installation directory. For example [jax](https://github.com/google/jax), [which only worked after I symlinked](https://github.com/google/jax/issues/989) `/usr/lib/cuda` to `/usr/local/cuda`

Is there a reason for this installation directory?

**Comment by mmstick** [comment]
`/usr/local` is for locally-installed packages & applications, not system-installed packages from the distribution. Debian packaging does not install files to `/usr/local`. Ideally these samples would be corrected to automatically detect the CUDA path.

**Comment by lhk** [comment]
oh, I didn't know that. Thanks for the clarification.
